#include <assert.h>
#include <curl/curl.h>
#include <curses.h>
#include <dlfcn.h> 
#include <errno.h>
#include <glib.h>
#include <json.h>
#include <locale.h>
#include <math.h> 
#include <readline/history.h>
#include <readline/readline.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdio.h> 
#include <stdlib.h> 
#include <stdnoreturn.h>
#include <string.h>
// #include <sys/inotify.h>
#include <sys/types.h>
#include <time.h> 
#include <unistd.h>
#include <unistd.h> 
#include <wchar.h>
#include <wctype.h>
